vim.keymap.set("n", "N", vim.cmd.tabnext)
vim.keymap.set("n", "D", vim.cmd.tabprevious)

vim.keymap.set("n", "X", vim.cmd.tabclose)

vim.keymap.set("n", "K", "")

vim.keymap.set("n", "d", "h")
vim.keymap.set("n", "h", "j")
vim.keymap.set("n", "t", "k")
vim.keymap.set("n", "n", "l")

vim.keymap.set("n", "gg", vim.cmd.NvimTreeToggle)
vim.keymap.set("n", "gf", vim.cmd.NvimTreeFocus)

vim.keymap.set("n", "yg", vim.cmd.UndotreeToggle)

vim.keymap.set('n', ';', 'a')
vim.keymap.set('n', ',', 'z')
vim.keymap.set('n', '.', 'e')
vim.keymap.set('n', 'p', 'r')
vim.keymap.set('n', 'y', 't')
vim.keymap.set('n', 'yy', 'tt')
vim.keymap.set('n', 'f', 'y')
vim.keymap.set('n', 'g', 'u')
vim.keymap.set('n', 'c', 'i')
vim.keymap.set('n', 'r', 'o')
vim.keymap.set('n', 'l', 'p')
vim.keymap.set('n', 'a', 'q')
vim.keymap.set('n', 'o', 's')
vim.keymap.set('n', 'e', 'd')
vim.keymap.set('n', 'u', 'f')
vim.keymap.set('n', 'i', 'g')
vim.keymap.set('n', 'd', 'h')
vim.keymap.set('n', 'h', 'j')
vim.keymap.set('n', 't', 'k')
vim.keymap.set('n', 'n', 'l')
vim.keymap.set('n', 's', 'm')
vim.keymap.set('n', "'", "w")
vim.keymap.set('n', 'q', 'x')
vim.keymap.set('n', 'j', 'c')
vim.keymap.set('n', 'k', 'v')
vim.keymap.set('n', 'x', 'b')
vim.keymap.set('n', 'b', 'n')
